server:
  port: 8086
spring:
  application:
    name: ly-user-service
  rabbitmq:
    host: 192.168.221.137
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      exchange: smsExchange
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
        publisher-confirms: true
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/leyou
      username: root
      password: 123
  redis:
    host: 192.168.221.137
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl