server:
  port: 8083
spring:
  application:
    name: ly-search
  jackson:
      default-property-inclusion: non_null # 配置json处理时忽略空值
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.221.137:9300
  rabbitmq:
    host: 192.168.221.137
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
